/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejerciciopropuesto18;

/**
 *
 * @author diego
 */
public class EmpleadoInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form EmpleadoInterfaz
     */
    public EmpleadoInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeroHoras = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        codigolabel = new javax.swing.JLabel();
        codigoLabel = new javax.swing.JLabel();
        codigotxt = new javax.swing.JTextField();
        nombrelabel = new javax.swing.JLabel();
        nombretxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        numeroHorastxt = new javax.swing.JTextField();
        valorHoras = new javax.swing.JLabel();
        valorhorastxt = new javax.swing.JTextField();
        porcentajeRetencion = new javax.swing.JLabel();
        porcentajeRetencionTxt = new javax.swing.JTextField();
        buttonInformation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        titulo.setText("Informacion Economica de Empleado");

        codigoLabel.setText("Codigo");

        codigotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigotxtActionPerformed(evt);
            }
        });

        nombrelabel.setText("Nombre");

        jLabel1.setText("Horas Trabajadas (h)");

        numeroHorastxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroHorastxtActionPerformed(evt);
            }
        });

        valorHoras.setText("Valor Horas ($)");

        valorhorastxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorhorastxtActionPerformed(evt);
            }
        });

        porcentajeRetencion.setText("Porcentaje de retencion (%)");

        porcentajeRetencionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentajeRetencionTxtActionPerformed(evt);
            }
        });

        buttonInformation.setText("Data");
        buttonInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInformationActionPerformed(evt);
            }
        });

        textArea1.setColumns(20);
        textArea1.setRows(5);
        jScrollPane1.setViewportView(textArea1);

        javax.swing.GroupLayout numeroHorasLayout = new javax.swing.GroupLayout(numeroHoras);
        numeroHoras.setLayout(numeroHorasLayout);
        numeroHorasLayout.setHorizontalGroup(
            numeroHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, numeroHorasLayout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(146, 146, 146))
            .addGroup(numeroHorasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(numeroHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(numeroHorasLayout.createSequentialGroup()
                        .addGroup(numeroHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codigolabel)
                            .addComponent(codigoLabel)
                            .addComponent(codigotxt)
                            .addComponent(jLabel1)
                            .addComponent(numeroHorastxt)
                            .addComponent(porcentajeRetencion)
                            .addComponent(porcentajeRetencionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(numeroHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valorhorastxt)
                            .addGroup(numeroHorasLayout.createSequentialGroup()
                                .addGroup(numeroHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombrelabel)
                                    .addComponent(valorHoras))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(nombretxt)))
                    .addGroup(numeroHorasLayout.createSequentialGroup()
                        .addComponent(buttonInformation)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        numeroHorasLayout.setVerticalGroup(
            numeroHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numeroHorasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(53, 53, 53)
                .addComponent(codigolabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(numeroHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(numeroHorasLayout.createSequentialGroup()
                        .addGroup(numeroHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(numeroHorasLayout.createSequentialGroup()
                                .addComponent(codigoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(numeroHorasLayout.createSequentialGroup()
                                .addComponent(nombrelabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroHorastxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(numeroHorasLayout.createSequentialGroup()
                        .addComponent(valorHoras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorhorastxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(porcentajeRetencion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(porcentajeRetencionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(buttonInformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numeroHoras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numeroHoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Creamos una instancia de la clase Empleado para poder utilizarla en todas
     * las funciones
     */
    Empleado employee = new Empleado();
    
    
    private void codigotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigotxtActionPerformed

    private void numeroHorastxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroHorastxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroHorastxtActionPerformed

    private void valorhorastxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorhorastxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorhorastxtActionPerformed

    private void porcentajeRetencionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentajeRetencionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_porcentajeRetencionTxtActionPerformed

    private void buttonInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInformationActionPerformed

        //asignamos la informacion escrito en los textfield a cada uno de los atributos correspondientes del objeto
        //Codigo del empleado
        employee.code=Integer.parseInt(codigotxt.getText());
        //Nombre del empleado
        employee.fName=nombretxt.getText();
        //Numero de horas trabajadas del empleado
        employee.nHours=Integer.parseInt(numeroHorastxt.getText());
        //Valor por hora para el empleado
        employee.valueHours=Double.parseDouble(valorhorastxt.getText());
        //porcentaje de retencion
        employee.percRetention=Double.parseDouble(porcentajeRetencionTxt.getText());
        
        //Limpiamos el area de texto para ingresar la nueva informacion
        textArea1.setText("");
        
        
        //Ahora presentamos el texto en el Area de texto
        //Nombre
        textArea1.append("Nombre: "+employee.fName+"\n");
        //Codigo
        textArea1.append("Codigo: "+employee.code+"\n");
        //Salario Brto
        textArea1.append("Salario Bruto: "+ employee.brutoSalary()+"\n");
        //Salario Neto
        textArea1.append("Salario Neto: "+employee.netoSalary()+"\n");
        
        
        
        
    }//GEN-LAST:event_buttonInformationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonInformation;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JLabel codigolabel;
    private javax.swing.JTextField codigotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombrelabel;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JPanel numeroHoras;
    private javax.swing.JTextField numeroHorastxt;
    private javax.swing.JLabel porcentajeRetencion;
    private javax.swing.JTextField porcentajeRetencionTxt;
    private javax.swing.JTextArea textArea1;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel valorHoras;
    private javax.swing.JTextField valorhorastxt;
    // End of variables declaration//GEN-END:variables
}
