/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package figurasgeometricas;

/**
 *
 * @author e420-00
 */
public class FigurasGeometricasInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form FigurasGeometricasInterfaz
     */
    public FigurasGeometricasInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRadioCirculo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAreaCirculo = new javax.swing.JTextField();
        txtPerimetroCirculo = new javax.swing.JTextField();
        btnAreaCirculo = new javax.swing.JButton();
        btnPerimetroCirculo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLadoCuadrado = new javax.swing.JTextField();
        txtAreaCuadrado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPerimetroCuadrado = new javax.swing.JTextField();
        btnAreaCuadrado = new javax.swing.JButton();
        btnPerimetroCuadrado = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtBaseRectangulo = new javax.swing.JTextField();
        txtAlturaRectangulo = new javax.swing.JTextField();
        btnAreaRectangulo = new javax.swing.JButton();
        btnPerimetroRectangulo = new javax.swing.JButton();
        txtAreaRectangulo = new javax.swing.JTextField();
        txtPerimetroRectangulo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtAlturaTrianguloRectangulo = new javax.swing.JTextField();
        txtBaseTrianguloRectangulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAreaTrianguloRectangulo = new javax.swing.JButton();
        btnPerimetroTrianguloRectangulo = new javax.swing.JButton();
        btnTipoTriangulo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTextTrianguloRectangulo = new javax.swing.JTextArea();
        btnHipotenusa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel9.setText("Figuras Geometricas");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        jLabel1.setText("Circulo");

        jLabel2.setText("Radio (m)");

        txtRadioCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRadioCirculoActionPerformed(evt);
            }
        });

        jLabel3.setText("Area (m²)");

        btnAreaCirculo.setText("Area (m²)");
        btnAreaCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaCirculoActionPerformed(evt);
            }
        });

        btnPerimetroCirculo.setText("Perimetro (m)");
        btnPerimetroCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroCirculoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        jLabel5.setText("Cuadrado");

        jLabel6.setText("Lado (m)");

        jLabel8.setText("Perimetro (m)");

        btnAreaCuadrado.setText("Area (m²)");
        btnAreaCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaCuadradoActionPerformed(evt);
            }
        });

        btnPerimetroCuadrado.setText("Perimetro (m)");
        btnPerimetroCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroCuadradoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        jLabel10.setText("Rectangulo");

        jLabel11.setText("Base (m)");

        btnAreaRectangulo.setText("Area (m²)");
        btnAreaRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaRectanguloActionPerformed(evt);
            }
        });

        btnPerimetroRectangulo.setText("Perimetro (m)");
        btnPerimetroRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroRectanguloActionPerformed(evt);
            }
        });

        jLabel13.setText("Base (m)");

        jLabel14.setText("Altura (m)");

        jLabel4.setText("Altura (m)");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        jLabel7.setText("Triangulo Rectangulo");

        btnAreaTrianguloRectangulo.setText("Area (m²)");
        btnAreaTrianguloRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaTrianguloRectanguloActionPerformed(evt);
            }
        });

        btnPerimetroTrianguloRectangulo.setText("Perimetro (m)");
        btnPerimetroTrianguloRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroTrianguloRectanguloActionPerformed(evt);
            }
        });

        btnTipoTriangulo.setText("Tipo");
        btnTipoTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoTrianguloActionPerformed(evt);
            }
        });

        areaTextTrianguloRectangulo.setColumns(20);
        areaTextTrianguloRectangulo.setRows(5);
        jScrollPane1.setViewportView(areaTextTrianguloRectangulo);

        btnHipotenusa.setText("Hipotenusa");
        btnHipotenusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHipotenusaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(txtRadioCirculo)
                                        .addComponent(txtAreaCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                    .addComponent(btnAreaCirculo))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPerimetroCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPerimetroCirculo)))
                            .addComponent(jLabel11)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBaseRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAreaRectangulo)
                                    .addComponent(txtAreaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPerimetroRectangulo)
                                    .addComponent(txtAlturaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(txtPerimetroRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(txtBaseTrianguloRectangulo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAlturaTrianguloRectangulo, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel4))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAreaTrianguloRectangulo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnHipotenusa)
                                        .addGap(227, 227, 227))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnPerimetroTrianguloRectangulo)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)
                                        .addComponent(txtLadoCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(txtAreaCuadrado))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(btnAreaCuadrado)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnPerimetroCuadrado))
                                        .addComponent(txtPerimetroCuadrado, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addComponent(btnTipoTriangulo)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRadioCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLadoCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAreaCuadrado)
                    .addComponent(btnPerimetroCuadrado))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(btnAreaCirculo)
                    .addComponent(btnPerimetroCirculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAreaCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPerimetroCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAreaCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPerimetroCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(btnAreaTrianguloRectangulo)
                    .addComponent(btnPerimetroTrianguloRectangulo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBaseRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlturaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlturaTrianguloRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAreaRectangulo)
                            .addComponent(btnPerimetroRectangulo)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBaseTrianguloRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPerimetroRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAreaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTipoTriangulo)
                    .addComponent(btnHipotenusa))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Definimos la instancias de los objetos necesarios fuera de los metodos
    // de tal manera que el ambito de los objetos abarque a todas los metodos
    //Circulo asignamos el parametro radio como 0
    Circulo circle = new Circulo(0);
    //Cuadrado asignamos el parametro lado como 0
    Cuadrado squart = new Cuadrado(0);
    //Rectangulo asignamos los parametros base y altura como 0
    Rectangulo rectangul = new Rectangulo(0,0);
    //Triangulo Rectangulo asignamos los parametro base y altura como 0
    TrianguloRectangulo trianguloRec = new TrianguloRectangulo(0, 0);
    
    private void btnPerimetroRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroRectanguloActionPerformed
        //Asigamos los parametros Base y Altura
        rectangul.base=Integer.parseInt(txtBaseRectangulo.getText());
        rectangul.altura=Integer.parseInt(txtAlturaRectangulo.getText());
        
        //Limpiamos el valor del textField
        txtPerimetroRectangulo.setText("");

        //Calculamos y asignamos el valor del Perimetro de rectangul
        txtPerimetroRectangulo.setText(Double.toString(rectangul.calcularPerimetro()));

    }//GEN-LAST:event_btnPerimetroRectanguloActionPerformed

    private void btnAreaRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaRectanguloActionPerformed

        //Asigamos los parametros Base y Altura
        rectangul.base=Integer.parseInt(txtBaseRectangulo.getText());
        rectangul.altura=Integer.parseInt(txtAlturaRectangulo.getText());

        //Limpiamos el txtField Area
        txtAreaRectangulo.setText("");

        //Calculamos y asignamos el valor del area de rectangul
        txtAreaRectangulo.setText(Double.toString(rectangul.calcularArea()));

    }//GEN-LAST:event_btnAreaRectanguloActionPerformed

    private void btnPerimetroCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroCuadradoActionPerformed
        //Asignamos el valor del parametro Lado ingresado en el txtField txtLadoCuadrado
        squart.lado=Integer.parseInt(txtLadoCuadrado.getText());

        //Limpiamos el txtField Perimetro
        txtPerimetroCuadrado.setText("");

        //Calculamos y asignamos el valor del Perimetro de squart
        txtPerimetroCuadrado.setText(Double.toString(squart.calcularPerimetro()));
    }//GEN-LAST:event_btnPerimetroCuadradoActionPerformed

    private void btnAreaCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaCuadradoActionPerformed
        //Asignamos el valor del parametro Lado ingresado en el txtField txtLadoCuadrado
        squart.lado=Integer.parseInt(txtLadoCuadrado.getText());

        //Limpiamos el txtField Area
        txtAreaCuadrado.setText("");

        //Calculamos y asignamos el valor del Area de squart
        txtAreaCuadrado.setText(Double.toString(squart.calcularArea()));

    }//GEN-LAST:event_btnAreaCuadradoActionPerformed

    private void btnPerimetroCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroCirculoActionPerformed
        //Asignamos el valor del parametro Radio al objeto circle
        circle.radio=Integer.parseInt(txtRadioCirculo.getText());

        //Limpiamos el valor en el textField txtPerimetroCirculo
        txtPerimetroCirculo.setText("");

        //Calculamos y Asignamos el valor del permitro de circle
        txtPerimetroCirculo.setText(Double.toString(circle.calcularPerimetro()));
    }//GEN-LAST:event_btnPerimetroCirculoActionPerformed

    private void btnAreaCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaCirculoActionPerformed
        //Asignamos el valor del parametro Radio al objeto circle
        circle.radio=Integer.parseInt(txtRadioCirculo.getText());

        //Limpiamos el valor en el textfield txtAreaCirculo
        txtAreaCirculo.setText("");

        //Calculamos y Asignamos el valor del area del circulo
        txtAreaCirculo.setText(Double.toString(circle.calcularArea()));
    }//GEN-LAST:event_btnAreaCirculoActionPerformed

    private void txtRadioCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRadioCirculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRadioCirculoActionPerformed

    private void btnAreaTrianguloRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaTrianguloRectanguloActionPerformed

        //Asignamos los valores de los Parametros Base y Altura al instancia trianguloRec
        trianguloRec.base=Integer.parseInt(txtBaseTrianguloRectangulo.getText());
        trianguloRec.altura=Integer.parseInt(txtAlturaTrianguloRectangulo.getText());
        
        //Limpiamos el valor en el textArea
        areaTextTrianguloRectangulo.setText("");
        
        //Calculamos el valor del area y lo presentamos el Area de texto
        areaTextTrianguloRectangulo.append("Area: "+trianguloRec.calcularArea()+" (m²)\n");
        
    }//GEN-LAST:event_btnAreaTrianguloRectanguloActionPerformed

    private void btnPerimetroTrianguloRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroTrianguloRectanguloActionPerformed
        //Asignamos los valores de los Parametros Base y Altura al instancia trianguloRec
        trianguloRec.base=Integer.parseInt(txtBaseTrianguloRectangulo.getText());
        trianguloRec.altura=Integer.parseInt(txtAlturaTrianguloRectangulo.getText());
        
        //Limpiamos el valor en el textArea
        areaTextTrianguloRectangulo.setText("");

        //Calculamos el valor del perimetro y lo presentamos el Area de texto
        areaTextTrianguloRectangulo.append("Perimetro: " + trianguloRec.calcularPerimetro()+" (m)\n");
       
    }//GEN-LAST:event_btnPerimetroTrianguloRectanguloActionPerformed

    private void btnHipotenusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHipotenusaActionPerformed
        //Asignamos los valores de los Parametros Base y Altura al instancia trianguloRec
        trianguloRec.base=Integer.parseInt(txtBaseTrianguloRectangulo.getText());
        trianguloRec.altura=Integer.parseInt(txtAlturaTrianguloRectangulo.getText());
        
        //Limpiamos el valor en el textArea
        areaTextTrianguloRectangulo.setText("");

        //Calculamos el valor del Hipotenusa y lo presentamos el Area de texto
        areaTextTrianguloRectangulo.append("Hipotenusa: " + trianguloRec.calcularHipotenusa()+" (m)\n");
    }//GEN-LAST:event_btnHipotenusaActionPerformed

    private void btnTipoTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoTrianguloActionPerformed
        //Asignamos los valores de los Parametros Base y Altura al instancia trianguloRec
        trianguloRec.base=Integer.parseInt(txtBaseTrianguloRectangulo.getText());
        trianguloRec.altura=Integer.parseInt(txtAlturaTrianguloRectangulo.getText());
        
        //Limpiamos el valor en el textArea
        areaTextTrianguloRectangulo.setText("");

        //Calculamos el tipo de triangulo y lo presentamos el Area de texto
        areaTextTrianguloRectangulo.append("El Triangulo es un: " + trianguloRec.determinarTipoTriangulo()+"\n");
    }//GEN-LAST:event_btnTipoTrianguloActionPerformed


    
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTextTrianguloRectangulo;
    private javax.swing.JButton btnAreaCirculo;
    private javax.swing.JButton btnAreaCuadrado;
    private javax.swing.JButton btnAreaRectangulo;
    private javax.swing.JButton btnAreaTrianguloRectangulo;
    private javax.swing.JButton btnHipotenusa;
    private javax.swing.JButton btnPerimetroCirculo;
    private javax.swing.JButton btnPerimetroCuadrado;
    private javax.swing.JButton btnPerimetroRectangulo;
    private javax.swing.JButton btnPerimetroTrianguloRectangulo;
    private javax.swing.JButton btnTipoTriangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlturaRectangulo;
    private javax.swing.JTextField txtAlturaTrianguloRectangulo;
    private javax.swing.JTextField txtAreaCirculo;
    private javax.swing.JTextField txtAreaCuadrado;
    private javax.swing.JTextField txtAreaRectangulo;
    private javax.swing.JTextField txtBaseRectangulo;
    private javax.swing.JTextField txtBaseTrianguloRectangulo;
    private javax.swing.JTextField txtLadoCuadrado;
    private javax.swing.JTextField txtPerimetroCirculo;
    private javax.swing.JTextField txtPerimetroCuadrado;
    private javax.swing.JTextField txtPerimetroRectangulo;
    private javax.swing.JTextField txtRadioCirculo;
    // End of variables declaration//GEN-END:variables
}
