/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Notas;
//Importamos la clase JFrame y las demas clases relaciondas con el paquete javax.swing
import javax.swing.*;



public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        //Cambiamo los parametros de la Ventana
        setTitle("Notas");
        setSize(280,380);
        setLocationRelativeTo(null);
        
        
        //Esblece que el boton de cerrar permita salir de la aplicacion
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false); //Establece que el tamaño de la ventana no se puede cambiar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notaUno = new javax.swing.JLabel();
        campoNotaUno = new javax.swing.JTextField();
        notaDos = new javax.swing.JLabel();
        campoNotaDos = new javax.swing.JTextField();
        notaTres = new javax.swing.JLabel();
        campoNotaTres = new javax.swing.JTextField();
        notaCuatro = new javax.swing.JLabel();
        campoNotaCuatro = new javax.swing.JTextField();
        notaCinco = new javax.swing.JLabel();
        campoNotaCinco = new javax.swing.JTextField();
        calcular = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cuadroInformacion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        notaUno.setText("Nota 1:");

        notaDos.setText("Nota 2:");

        campoNotaDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNotaDosActionPerformed(evt);
            }
        });

        notaTres.setText("Nota 3:");

        campoNotaTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNotaTresActionPerformed(evt);
            }
        });

        notaCuatro.setText("Nota 4:");

        notaCinco.setText("Nota 5:");

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        cuadroInformacion.setColumns(20);
        cuadroInformacion.setRows(5);
        cuadroInformacion.setText("Promedio:\n \nDesviacion estandar:\n \nValor mayor:\n \nvalor menor:\n");
        jScrollPane1.setViewportView(cuadroInformacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notaUno)
                            .addComponent(notaDos)
                            .addComponent(notaTres)
                            .addComponent(notaCuatro)
                            .addComponent(notaCinco))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoNotaCuatro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNotaCinco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNotaDos)
                            .addComponent(campoNotaTres)
                            .addComponent(campoNotaUno)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calcular)
                        .addGap(18, 18, 18)
                        .addComponent(limpiar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notaUno)
                    .addComponent(campoNotaUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notaDos)
                    .addComponent(campoNotaDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notaTres)
                    .addComponent(campoNotaTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notaCuatro)
                    .addComponent(campoNotaCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notaCinco)
                    .addComponent(campoNotaCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limpiar)
                    .addComponent(calcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Instaciamos la clase Notas
    Notas notas = new Notas();
    
    private void campoNotaDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNotaDosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNotaDosActionPerformed

    private void campoNotaTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNotaTresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNotaTresActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed

        //Evaluamos si los campo estan vacios
        boolean vacioUno=campoNotaUno.getText().trim().isEmpty();
        boolean vacioDos=campoNotaDos.getText().trim().isEmpty();
        boolean vacioTres=campoNotaTres.getText().trim().isEmpty();
        boolean vacioCuatro=campoNotaCuatro.getText().trim().isEmpty();
        boolean vacioCinco=campoNotaCinco.getText().trim().isEmpty();
        
        
        
        if (vacioUno||vacioDos||vacioTres||vacioCuatro||vacioCinco){
         JOptionPane.showMessageDialog(null,"Debe de ingresar los datos\nen todos los campos de texto", "Error",JOptionPane.ERROR_MESSAGE);   
        }
        else{

        
            //Asiganmos los valores ingresados a los parametros del Objeto
            notas.listaNotas[0]=Double.parseDouble(campoNotaUno.getText());    //Nota 1
            notas.listaNotas[1]=Double.parseDouble(campoNotaDos.getText());    //Nota 2
            notas.listaNotas[2]=Double.parseDouble(campoNotaTres.getText());   //Nota 3
            notas.listaNotas[3]=Double.parseDouble(campoNotaCuatro.getText()); //Nota 4
            notas.listaNotas[4]=Double.parseDouble(campoNotaCinco.getText());  //Nota 5

            cuadroInformacion.setText("");
                    
            cuadroInformacion.append("Promedio = "+String.valueOf(String.format("%.2f", notas.calcularPromedio())) +"\n\n");
            cuadroInformacion.append("Desviacion estandar = "+ String.valueOf(String.format("%.2f",notas.calcularDesviacion()))+"\n\n");
            cuadroInformacion.append("Valor mayor = "+String.valueOf(String.format("%.2f",notas.calcularMayor()))+"\n\n");
            cuadroInformacion.append("Valor menor = "+String.valueOf(String.format("%.2f",notas.calcularMenor()))+"\n");
            
        }
    }//GEN-LAST:event_calcularActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        //Limpiamos el area de texto
        cuadroInformacion.setText("Promedio: \n\nDesviacion estandar:\n\nValor mayor:\n\nvalor menor:\n");
        //Ademas limpiamos los campos de texto 
        campoNotaUno.setText("");
        campoNotaDos.setText("");
        campoNotaTres.setText("");
        campoNotaCuatro.setText("");
        campoNotaCinco.setText("");
    }//GEN-LAST:event_limpiarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JTextField campoNotaCinco;
    private javax.swing.JTextField campoNotaCuatro;
    private javax.swing.JTextField campoNotaDos;
    private javax.swing.JTextField campoNotaTres;
    private javax.swing.JTextField campoNotaUno;
    private javax.swing.JTextArea cuadroInformacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JLabel notaCinco;
    private javax.swing.JLabel notaCuatro;
    private javax.swing.JLabel notaDos;
    private javax.swing.JLabel notaTres;
    private javax.swing.JLabel notaUno;
    // End of variables declaration//GEN-END:variables
}
